# config/packages/security.yaml

security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        # Для страницы логина
        login:
            pattern: ^/kab$
            security: false

        # Главная страница с аутентификацией
        main:
            pattern: ^/
            form_login:
                login_path: show_kab
                check_path: show_kab
                default_target_path: home
            logout:
                path: app_logout
                target: show_kab

    access_control:
        - { path: ^/kab, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
