
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        login:
            pattern: ^/kab$
            security: false  

        public:
            pattern: ^/register$
            security: false  

        main:
            pattern: ^/
            form_login:
                login_path: show_kab
                check_path: show_kab
                username_parameter: username
                password_parameter: password
                default_target_path: show_conference
            logout:
                path: app_logout
                target: show_kab

    access_control:
        - { path: ^/kab, roles: IS_AUTHENTICATED_ANONYMOUSLY }   
        - { path: ^/conference, roles: IS_AUTHENTICATED_ANONYMOUSLY } 

