controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

show_kab:
    path: /kab
    controller: App\Controller\KabController::loginAction





